name: Tests

on:
  push:
    branches: [main, project-experimental]
  pull_request:
    branches: [main, project-experimental]

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3']
    
    name: PHP ${{ matrix.php-version }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      
      - name: Run test suite
        run: vendor/bin/phpunit
